---
session_name: dev-${PWD}
start_directory: ${PWD}
windows:
  - layout: main-vertical
    options:
      main-pane-width: 120
    panes:
      - shell_command:
          - nvim
        focus: true
      - pane
